### PR TITLE
init-container.sh: change cbt branch name

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
To make it more consistent with the existing branch names.

**Comment by Frezzle** [comment]
1) Is this needed? If so, should we change all the others?
2) Is there a corresponding change in upload-scripts?

**Comment by gaborigloi** [comment]
1. Yes, because all our CBT branches on github are called `feature/CBT`.
2. I think this doesn't affect the uploading, this is just to make sure that the correct XS branch will be selected based on the name of the GitHub branch.

**Review by Frezzle — APPROVED** [review]

**Comment by gaborigloi** [comment]
Thanks for the review!:)

**Pull request merged**
