### PR TITLE
Travis builds: Allow to explicitly set XS branch name; add support for falcon

### PR DESCRIPTION
**Pull request by gaborigloi**
This gives us more flexibility, so we don't have to follow the name of
the main XS branch for each component, now we can explicitly set which
branch a given component branch belongs to. This can be done by adding
the GIT_BRANCH variable to the .travis.yml of the repo to be tested.

If it is not specified, then the name of the branch will be used, as
previously, this provides backward-compatibility, so that the builds of
the older branches will not get broken.

This is necessary to fix the Travis build of the 1.30-lcm branch of
xen-api.

### CODE REVIEW

**Review by mseri — APPROVED** [review]
I it find annoying that we need to remember to specify the branches, but this is something that changes rarely after all and I don't see a better solution for the moment

**Comment by gaborigloi** [comment]
Yep, we need this because for falcon, we apparently adopted a new branch naming strategy: the different component branches have different names ( like `1.30-lcm` for xen-api, `0.24-lcm` for xenopsd), therefore we cannot determine the XenServer branch name for the git branch name.

**Comment by mseri** [comment]
Merging now then, trusting the local test

**Comment by gaborigloi** [comment]
The Travis build passed on my branch: https://travis-ci.org/gaborigloi/xenserver-build-env

**Pull request merged**
