### PR TITLE
Add a -v option

### PR DESCRIPTION
**Pull request by robhoes**
Signed-off-by: Rob Hoes rob.hoes@citrix.com

### CODE REVIEW

**Comment by johnelse** [comment]
pep8 doesn't like the blank line 105

**Comment by simonjbeaumont** [comment]
Maybe we should relax the constraint on the `-d` option or remove it since they are doing the same thing. Also `-v` is a bit of a standard option letter, is there anything else we can use that I wouldn't associate with verbosity if we decide to not modify the `-d` option?

**Comment by simonjbeaumont** [comment]
Discussed this with rob and it might be nicer do things in terms of `-v`s since this is an option to docker so this option is effectively transparently passed through to the docker CLI. We should think about whether we want to keep `-d` and the `--syslog` options since they are shortcuts for things that could be done with `-v`.

**Comment by robhoes** [comment]
I've removed the blank line that pep8 was complaining about.

**Pull request merged**
